### ISSUE TITLE
Documentation Update: Simple Newsletter Example With No External Dependencies

### ISSUE THREAD

**Issue by urbanophile** [ziolko/spreadapi#13]
Hi, first I want to thank you for making this lovely library.

 I think a slight change to the documentation would be helpful: the existing newsletter example uses two external dependencies: Bulma and jQuery. They are fine tools, but it would be beneficial to have a very, very simple example that you can get working just by cutting and pasting. I think people might be also be interested in an example using Cloudflare workers. 

I am happy to write both examples and submit a pull request, but it's not clear to me how to make an edit for the documentation. Would you be receptive to such a pull request?

**Comment by ziolko** [comment]
Hi @urbanophile,

Thank you for raising this issue. The documentation is currently hosted on Gitbook. I've just enabled integration with Github so you can find the source code at https://github.com/ziolko/spreadapi/tree/master/website. Unfortunately there's no preview for your changes but feel free to raise a PR and I will adjust it if something is off after merging it.

Your help is highly appreciated!

Mateusz

**Comment by DylanSp** [comment]
Given that Bulma and jQuery can both be loaded via `<script>` tags, maybe it'd be easy to just have a single self-contained HTML file with the full example, which loads Bulma and jQuery via `<script>`, and contains the necessary JS in a `<script>` as well? That might be easier than rewriting the example.

**Comment by DylanSp** [comment]
I built a self-contained HTML file in my fork [here](https://github.com/DylanSp/spreadapi/blob/self-contained-signup-example/website/examples/sign-up-form-example.html), and created a [draft PR](https://github.com/ziolko/spreadapi/pull/14) to add it to the repo. I tested it with a Google Sheet I set up, it works.

**Comment by DylanSp** [comment]
This can probably be closed, now that https://github.com/ziolko/spreadapi/pull/14 is merged.

**Comment by ziolko** [comment]
Right! Thanks for your contribution @DylanSp :)

**Comment by DylanSp** [comment]
Glad to help out!
