### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by jaroslavas** [ziolko/spreadapi#15]
How do you guys solve problem with CORS? 
I'm trying to run code from documentation, bet then when I make request from my frontend app, browser blocks the request and throws CORS error.

**Comment by ziolko** [comment]
Hi @jaroslavas,

Could you take a look at this example: https://jsfiddle.net/mkzL9ver/27/? It doesn't have any issue with CORS so perhaps you can just take the same approach.

**Comment by ziolko** [comment]
Hi @jaroslavas. I will close this ticket due to lack of activity from your side.

Cheers,
Mateusz

**Comment by jaroslavas** [comment]
OK, I just switched to reading json on my backend and caching it, which is overall a better solution, keeping in mind that google has quite low rate limits.
