### ISSUE TITLE
Always returns a 401 with message "unauthorized" for non-lowercased sheet names

### ISSUE THREAD

**Issue by vereis** [ziolko/spreadapi#2]
https://github.com/ziolko/spreadapi/blob/76d4291f91833c06e2c8eb1e4aa29bbb572d8b97/spread-api.js#L67

I have been using this for awhile but was migrating to a new sheet when suddenly stuff stopped working. One of the only changes was that our sheet was renamed from `test_sheet` to `TEST_SHEET`.

Started looking into the causes of the 401's being returned and I think it's because we do a `.toLowercase()` on the sheet names coming in, but I don't see where we lowercase them when setting a `User`'s permissions, nor in the documentation for Google's actual API.

I think it should be safe to simply remove this `.toLowercase()` call, unless I'm missing something 😅

**Comment by ziolko** [comment]
Hi, I've addressed this in https://github.com/ziolko/spreadapi/commit/1ba3656c149847d7928a74909bd8ef5387bb9151. I'd like to keep the case-insensitiveness of sheet names. 

Try the non-minified version (https://github.com/ziolko/spreadapi/blob/master/spread-api.js) and if it works well I will update the minified version as well.

Cheers,
Mateusz
