### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by julius-tuliao** [ziolko/spreadapi#3]
I'm trying to use this spreadapi on one of my project but I'm encountering this error.

Status :401
code:unauthorized

I've followed your demo on youtube but it still won't work . Any idea on what I might not be doing right?

![image](https://user-images.githubusercontent.com/27881527/98217400-6c1ec780-1f85-11eb-947c-7e40bb276bd9.png)

**Comment by ziolko** [comment]
Hi, sorry for the late response. Perhaps this is the manifestation of #2 ? Please try to rename sheets to lowercase and let me know if this helps.

**Comment by julius-tuliao** [comment]
Hi sorry just seen your response. Thank you
