### ISSUE TITLE
Can't get it to work with curl

### ISSUE THREAD

**Issue by gcleaves** [ziolko/spreadapi#5]
Hi, any idea why I'm having trouble getting a response when using curl? It works fine with wget and Postman.

`curl -L -X POST 'https://script.google.com/macros/s/hidden/exec' --data-raw '{"method": "GET", "sheet": "data", "key": "a_good_password"}'`

As a response I get "Sorry, the file you have requested does not exist."

**Comment by ziolko** [comment]
Hi, The following command works for me. Perhaps you can build your request based on this?

`curl -L https://script.google.com/macros/s/AKfycbyhsZxwsFru3uF5boPaVPqYH3lVHr-tOZKr_iFJ5eB6X8byg5-hMgs-UCsMvXsDn5gwNQ/exec --data '{"method": "GET", "sheet": "sheet"}'`

Best,
Mateusz
