### ISSUE TITLE
isStrongKey doesn't allow many valid special characters

### ISSUE THREAD

**Issue by gcleaves** [ziolko/spreadapi#6]
Hi. Currently `isStrongKey` only considers the following special characters: `!@#$%^&*` . This excludes many possible ASCII special characters. I recommend you update the regex to: 

`^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\x20-\x2F\x3A-\x40\x5B-\x60\x7B-\x7E])(?=.{8,})`

I have included several ranges from this table: http://www.asciitable.com/

**Comment by ziolko** [comment]
I think it's a good point. I will add it in the next few days.

**Comment by ziolko** [comment]
Done. Let me know if it works fine for you.
