### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by laufert** [ziolko/spreadapi#9]
Hi,

thanks a lot for your project. Unfortunately I realized today that your documentation at https://spreadapi.com/ is down. Is it possible to bring the documentation up again?

For all fellow Spread-API users: 
  You can access the last version of the documentation via the Internet Archive -> https://web.archive.org/web/20210527031526/https://spreadapi.com/

Thanks a lot,
Tilo

**Comment by ziolko** [comment]
Hi @laufert. Thanks for bringing this up! As the domain has already been bought by someone else, I deployed docs at https://spreadapi.roombelt.com. 

Please let me know if it works for you.

Mateusz

**Comment by laufert** [comment]
Hi @ziolko,

Thanks a lot for bringing the docs up again so quickly! https://spreadapi.roombelt.com/ works like a charm. Thanks for updating the Docs as well ^^

Thanks a lot,
Tilo
